#!/usr/bin/env php
<?php

require_once __DIR__ . '/bootstrap.php';

use Symfony\Component\Console\Application;
use Martiis\CheckoutServer\Payment\Command\PaymentCommand;
use Martiis\CheckoutServer\Queue\Command\QueueCommand;
use Martiis\CheckoutServer\Queue\Command\AddCommand;
use Martiis\CheckoutServer\Storage\Command\StorageCommand;

$app = new Application('Checkout Server Application', '0.1');

$app->add(new PaymentCommand());
$app->add(new StorageCommand());
$app->add(new QueueCommand());
$app->add(new AddCommand());

$app->run();
