#!/usr/bin/env php
<?php

require_once __DIR__ . '/bootstrap.php';

use Symfony\Component\Console\Application;
use Martiis\CheckoutServer\Basket\Command\AddCommand;
use Martiis\CheckoutServer\Basket\Command\RemoveCommand;
use Martiis\CheckoutServer\Basket\Command\CleanCommand;
use Martiis\CheckoutServer\Basket\Command\CheckoutCommand;

$app = new Application('Checkout Server Application', '0.1');

$app->add(new AddCommand());
$app->add(new RemoveCommand());
$app->add(new CleanCommand());
$app->add(new CheckoutCommand());

$app->run();
